# Generated by Django 4.1.13 on 2024-01-06 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airport_Security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('face_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('faces', models.ImageField(upload_to='face_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('mobile_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits long.', regex='^\\d{10}$')])),
                ('flight_number', models.CharField(max_length=50)),
                ('plane_number', models.CharField(max_length=50)),
                ('booked_Date', models.DateField()),
                ('booked_Time', models.DateTimeField()),
                ('passport_number', models.CharField(max_length=50)),
                ('flight_Destination_from', models.CharField(max_length=50)),
                ('flight_Destination_to', models.CharField(max_length=50)),
                ('flight_Destination_Duration', models.DateTimeField()),
                ('depature_date', models.DateField()),
                ('depature_time', models.DateTimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('mobile_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits long.', regex='^\\d{10}$')])),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(max_length=50)),
                ('face_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airport_Security.face')),
            ],
        ),
    ]
