# Generated by Django 4.1.12 on 2023-10-12 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airport_Security', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits long.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits long.', regex='^\\d{10}$')]),
        ),
    ]
