# Generated by Django 4.1.13 on 2024-01-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airport_Security', '0010_passenger_passenger_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='flight_Destination_Duration',
        ),
    ]
