# Generated by Django 4.1.13 on 2024-01-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airport_Security', '0011_remove_passenger_flight_destination_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='faces',
            field=models.ImageField(null=True, upload_to='face_images/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='face_id',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='Face',
        ),
    ]
